import Head from "next/head";
import { Inter } from "next/font/google";
import { BsFillMoonStarsFill, BsDiscord } from "react-icons/bs";
import { AiFillGithub, AiFillYoutube } from "react-icons/ai";
import { useState } from "react";
import Image from "next/image";

// Images
import Avatar from "../public/Avatar.png";

// Experience Images
import html from "../public/html.png";
import css from "../public/css.png";
import javascript from "../public/javascript.png";
import reactImage from "../public/react.png";
import csharp from "../public/csharp.png";
import tailwind from "../public/tailwind.png";

// Experience
const techs = [
  {
    id: 1,
    src: html,
    title: "HTML",
    style: "shadow-orange-500",
  },
  {
    id: 2,
    src: css,
    title: "CSS",
    style: "shadow-blue-500",
  },
  {
    id: 3,
    src: javascript,
    title: "JavaScript",
    style: "shadow-yellow-500",
  },
  {
    id: 4,
    src: reactImage,
    title: "React",
    style: "shadow-blue-600",
  },
  {
    id: 5,
    src: tailwind,
    title: "Tailwind",
    style: "shadow-sky-400",
  },
  {
    id: 8,
    src: csharp,
    title: "Csharp",
    style: "shadow-pink-400",
  },
];

// Portfolio Images
import oplservernde from "../public/portfolio/oplservernde.jpg";
// Portfolio Projects
const projects = [
  {
    id: 1,
    src: oplservernde,
    title: "OPL Server NDE",
    demo: "https://github.com/pedronicolasg/OPL-Server-NDE/releases",
    code: "https://github.com/pedronicolasg/OPL-Server-NDE",
  },
];

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Pedro Nícolas - Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl font-bold">NÍCOLAS DEV</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>

              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Pedro Nícolas
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Um jovem programador em aprendizado.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://discord.gg/NugmkDfvuj"><BsDiscord /></a>
              <a href="https://github.com/pedronicolasg"><AiFillGithub /></a>
              <a href="https://www.youtube.com/channel/UCrITwhAHifiYeksl7T7wPzg"><AiFillYoutube /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={Avatar} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Experiência</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Estas são as <span className="text-teal-500">tecnologias</span> com as quais tenho experiência
            </p>
          </div>
          <div className="md:flex gap-10">
            {techs.map(({ id, src, title, style }) => (
              <div
                key={id}
                className={`lg:w-96 text-center m-5 bg-gray-800 text-white py-5 shadow-md hover:scale-105 duration-500 rounded-lg ${style} dark:text-gray-800 dark:bg-white`}

              >
                <Image src={src} className="w-20 mx-auto" />
                <p className="mt-4">{title}</p>
              </div>
            ))}
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfólio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Confira um pouco dos meus projetos aqui</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap align-middle">
            {projects.map(({ id, src, title, demo, code }) => (
              <div key={id} className="w-96 bg-gray-800 text-white shadow-md shadow-gray-800 text-center rounded-lg dark:text-gray-800 dark:bg-white">
                <p className="mt-4 pb-5 font-bold">{title}</p>
                <Image
                  src={src}
                  className="rounded-md duration-200 hover:scale-105"
                />
                <div className="flex items-center justify-center">
                  <button className="w-1/2 px-6 py-3 m-4 duration-200 hover:scale-105">
                    <a href={demo}>Demo</a>
                  </button>
                  <button className="w-1/2 px-6 py-3 m-4 duration-200 hover:scale-105">
                    <a href={code}>Código</a>
                  </button>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
